version: '2.3'
services:
  nmap-agent:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - default
    working_dir: /app
    environment:
      - SCAN_NETWORK=192.168.10.*
      - SCAN_TCP_PORTS=20,21,22,23,25,80,110,443,512,522,8080,1080,22222
    command: ["/app/bin/scan"]
