version: '2.3'
services:
  nmap-agent:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - default
    working_dir: /app
    environment:
      - SCAN_NETWORK=192.168.10.1/32
      - SCAN_TCP_PORTS=20,21,22,23,25,80,110,443,512,522,8080,1080,22222
      - SCAN_COOLOFF=60
      - AWS_REGION=INSERT_AWS_REGION
      - AWS_S3_BUCKET=INSERT_AWS_S3_BUCKET
      - AWS_ACCESS_KEY_ID=INSERT_AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=INSERT_AWS_SECRET_ACCESS_KEY
    command: ["/app/bin/scan"]
